Updating README to have more background, example usage, and more detailed installation instructions
facebookexperimental/rn-chrome-devtools-frontend pull request #119
Opened 2024-09-25 20:31 UTC by maxlindbergh

# Summary

I've added some project background to make the goals and capabilities of this project more clear to people not familiar with the codebase. Additionally, I've added an "Example Usage" section to the README so that it is, again, more clear to new users how they can use this software.

Finally, I've added a bit of description to each of the three installation options. I've put in some information on how they differ and when each case should be used.

# Test plan

This is purely a documentation change so no real testing is required.

2024-10-15 10:28 UTC, hoxyq approved these changes
Thanks.

2024-10-15 10:36 UTC, hoxyq requested changes
Sorry, missed this one. We only use `rn_fusebox` as a custom entrypoint for React Native applications.

2024-10-15 10:36 UTC, hoxyq commented on README.md
> +your browser using Chrome DevTools.
```suggestion
Then, open your browser and navigate to http://localhost:8000/rn_fusebox.html for 
React Native-specific debugging.
```

2024-11-19 18:14 UTC, huntie commented on README.md
> +
These bits feel too verbose (AI generated?) — these scripts are self-documenting. Intend to come back and merge this PR, but let's do a pass of the file which removes these.

2024-11-29 18:08 UTC, closed without merging